# Generated by Django 4.0.8 on 2024-06-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.CharField(max_length=255, null=True)),
                ('NOM_Prénom', models.CharField(default='Default Name', max_length=255)),
                ('Nom_du_compte', models.CharField(max_length=255)),
                ('Mot_de_passe', models.CharField(max_length=255)),
                ('NOM_MACHINE_actuel', models.CharField(max_length=255, null=True)),
                ('Type_machine', models.CharField(max_length=255)),
                ('ram_installé', models.CharField(max_length=255)),
                ('Carte_graphique', models.CharField(max_length=255, null=True)),
                ('Emplacement', models.CharField(max_length=255)),
            ],
        ),
    ]
